[phases.setup]
nixPkgs = ["nodejs_22", "bun"]

[phases.install]
cmds = [
  "npm ci",
  "cd backend && npm ci"
]

[phases.build]
cmds = [
  "npx vite build",
  "cd backend && npm run build"
]

[start]
cmd = "cd backend && npm start" 