[phases.setup]
nixPkgs = ["nodejs_22", "bun"]

[phases.install]
cmds = [
  "chmod +x build.sh",
  "npm ci --include=optional",
  "cd backend && npm ci"
]

[phases.build]
cmds = ["./build.sh"]

[start]
cmd = "cd backend && npm start" 