[phases.setup]
nixPkgs = ["nodejs_22", "bun"]

[phases.install]
cmds = [
  "npm install",
  "cd backend && npm install"
]

[phases.build]
cmds = ["bash build.sh"]

[start]
cmd = "cd backend && npm start" 